import { expect, test } from "@playwright/test";

test("successfully view file", async ({ page }) => {
  await page.goto("http://localhost:8000/");
  await page.getByLabel("Login").click();
  await expect(page.getByLabel("Sign Out")).toBeVisible();
  var mock_input = `load dataset1`;
  await page.getByLabel("Command input").click();
  await page.getByLabel("Command input").fill(mock_input);
  await page.getByText("Submit (0)").click();
  await expect(page.getByText("Loaded dataset1")).toBeVisible();
  mock_input = `view`;
  await page.getByLabel("Command input").click();
  await page.getByLabel("Command input").fill(mock_input);
  await page.getByText("Submit (1)").click();
  await expect(page.getByText("Brown St")).toBeVisible();
  mock_input = `search 1 Brown`;
  await page.getByLabel("Command input").click();
  await page.getByLabel("Command input").fill(mock_input);
  await page.getByText("Submit (2)").click();
  mock_input = `mode`;
  await page.getByLabel("Command input").click();
  await page.getByLabel("Command input").fill(mock_input);
  await page.getByText("Submit (3)").click();
  await expect(page.getByText("Changed mode to verbose")).toBeVisible();
  await page.getByLabel("Command input").click();
  await page.getByLabel("Command input").fill(mock_input);
  await page.getByText("Submit (4)").click();
  await expect(page.getByText("Changed mode to brief ")).toBeVisible();
  mock_input = `load dataset2`;
  await page.getByLabel("Command input").click();
  await page.getByLabel("Command input").fill(mock_input);
  await page.getByText("Submit (5)").click();
  await expect(page.getByText("Loaded dataset2")).toBeVisible();
  mock_input = `view`;
  await page.getByLabel("Command input").click();
  await page.getByLabel("Command input").fill(mock_input);
  await page.getByText("Submit (6)").click();
  mock_input = `search 0 Dog Ave`;
  await page.getByLabel("Command input").click();
  await page.getByLabel("Command input").fill(mock_input);
  await page.getByText("Submit (7)").click();
});
